version: '3.6'
services:
  php:
    build: 'docker/images/php/'
    volumes:
      - '.:/var/www/html'
      - './docker/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'
    depends_on:
      - database
  database:
    image: 'mariadb'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: 'adminer'
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade